### ISSUE TITLE
Hardcoded string

### ISSUE THREAD

**Issue by harbingerofme** [KomradeSpectre/ItemModCreationBoilerplate#1]
https://github.com/KomradeSpectre/ItemModCreationBoilerplate/blob/830e6b0a2a487c7fa5c49b25c06a45ce9f046487/ItemModCreationBoilerplate/Main.cs#L34

Please consider using the `public const string ModName`

**Comment by KomradeSpectre** [comment]
Sure, I can do this. Do you mean for me to have that be "@" + ModName, MainAssets ?

**Comment by KomradeSpectre** [comment]
Fixed in #2
